//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraduateThesisSystem.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TezDBEntities : DbContext
    {
        public TezDBEntities()
            : base("name=TezDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBaslik> TBaslik { get; set; }
        public virtual DbSet<TDanisman> TDanisman { get; set; }
        public virtual DbSet<TDil> TDil { get; set; }
        public virtual DbSet<TEnstitu> TEnstitu { get; set; }
        public virtual DbSet<TTez> TTez { get; set; }
        public virtual DbSet<TTip> TTip { get; set; }
        public virtual DbSet<TUniversite> TUniversite { get; set; }
        public virtual DbSet<TYazar> TYazar { get; set; }
    }
}
