//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraduateThesisSystem.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTez
    {
        public int TezNo { get; set; }
        public Nullable<int> Baslik { get; set; }
        public string Tez { get; set; }
        public int Yazar { get; set; }
        public string Yil { get; set; }
        public Nullable<int> Tip { get; set; }
        public Nullable<int> Universite { get; set; }
        public Nullable<int> Enstitu { get; set; }
        public string SayfaSayisi { get; set; }
        public Nullable<int> Dil { get; set; }
        public string TeslimTarih { get; set; }
        public Nullable<int> Danisman { get; set; }
    
        public virtual TBaslik TBaslik { get; set; }
        public virtual TDanisman TDanisman { get; set; }
        public virtual TDil TDil { get; set; }
        public virtual TEnstitu TEnstitu { get; set; }
        public virtual TTip TTip { get; set; }
        public virtual TUniversite TUniversite { get; set; }
        public virtual TYazar TYazar { get; set; }
    }
}
